/******************************************************************************
  Title          : iso_limits2.c
  Author         : Stewart Weiss
  Created on     : January 27, 2011
  Description    : Displays the values of the ISO C static constants 
  Purpose        : To show the values of the ISO C limits on the given system.
  Usage          : iso_limits
  Build with     : gcc -o iso_limits iso_limits.c
  Modifications  : March 8, 2011
                   This version cntains all of the conditional compilation
                   guards so that the code will compile on systems that are
                   not ISO C compliant.
  Notes          : The constants whose names appear in the print statements
                   below are defined in the file <limits.h> on an ISO-C99 
                   compliant implementation of UNIX. These are compile-time
                   limits. 

                   The actual values that are displayed when this program is 
                   run may be larger than the values specified in the ISO C
                   standard, which specifies MINIMUMs for these values.

                   When you run this, look at the values of CHAR_MAX and 
                   CHAR_MIN. If they are the same as those of SCHAR_MAX and
                   SCHAR_MIN, then characters are signed values. If characters
                   are unsigned, then CHAR_MIN will be 0.
 
******************************************************************************/

#include <limits.h>
#include <stdio.h>

int main()
{

#ifdef __STDC__
    printf("The compiler supports ISO C.\n\n");
#else
    printf("The compiler does not support ISO C fully,\n\n");
#endif

#ifdef CHAR_BIT
    printf("%-12s:%20d\n","CHAR_BIT", CHAR_BIT);
#else
    printf("CHAR_BIT is not defined on this system.\n");
#endif

#ifdef CHAR_MAX
    printf("%-12s:%20d\n","CHAR_MAX", CHAR_MAX);
#else
    printf("CHAR_MAX is not defined on this system.\n");
#endif

#ifdef CHAR_MIN
    printf("%-12s:%20d\n","CHAR_MIN", CHAR_MIN);
#else
    printf("CHAR_MIN is not defined on this system.\n");
#endif

#ifdef SCHAR_MAX
    printf("%-12s:%20d\n","SCHAR_MAX", SCHAR_MAX);
#else
    printf("SCHAR_MAX is not defined on this system.\n");
#endif

#ifdef SCHAR_MIN
    printf("%-12s:%20d\n","SCHAR_MIN", SCHAR_MIN);
#else
    printf("SCHAR_MIN is not defined on this system.\n");
#endif

#ifdef UCHAR_MAX
    printf("%-12s:%20u\n","UCHAR_MAX", UCHAR_MAX);
#else
    printf("UCHAR_MAX is not defined on this system.\n");
#endif
    
#ifdef INT_MAX
    printf("%-12s:%20d\n","INT_MAX", INT_MAX);
#else
    printf("INT_MAX is not defined on this system.\n");
#endif
    
#ifdef INT_MIN
    printf("%-12s:%20d\n","INT_MIN", INT_MIN);
#else
    printf("INT_MIN is not defined on this system.\n");
#endif
    
#ifdef UINT_MAX
    printf("%-12s:%20u\n","UINT_MAX", UINT_MAX);
#else
    printf("UINT_MAX is not defined on this system.\n");
#endif
    
#ifdef SHRT_MAX
    printf("%-12s:%20d\n","SHRT_MAX", SHRT_MAX);
#else
    printf("SHRT_MAX is not defined on this system.\n");
#endif
    
#ifdef USHRT_MAX
    printf("%-12s:%20u\n","USHRT_MAX", USHRT_MAX);
#else
    printf("USHRT_MAX is not defined on this system.\n");
#endif
    
#ifdef LONG_MAX
    printf("%-12s:%20ld\n","LONG_MAX", LONG_MAX);
#else
    printf("LONG_MAX is not defined on this system.\n");
#endif
   
#ifdef LONG_MIN
    printf("%-12s:%20ld\n","LONG_MIN", LONG_MIN);
#else
    printf("LONG_MIN is not defined on this system.\n");
#endif
   
#ifdef ULONG_MAX
    printf("%-12s:%20lu\n","ULONG_MAX", ULONG_MAX);
#else
    printf("ULONG_MAX is not defined on this system.\n");
#endif

#ifdef LLONG_MAX
    printf("%-12s:%20lld\n","LLONG_MAX", LLONG_MAX);
#else
    printf("LLONG_MAX is not defined on this system.\n");
#endif

#ifdef LLONG_MIN
    printf("%-12s:%20lld\n","LLONG_MIN", LLONG_MIN);
#else
    printf("LLONG_MIN is not defined on this system.\n");
#endif

#ifdef ULLONG_MAX
    printf("%-12s:%20llu\n","ULLONG_MAX", ULLONG_MAX);
#else
    printf("ULLONG_MAX is not defined on this system.\n");
#endif

#ifdef MB_LEN_MAX
    printf("%-12s:%20d\n","MB_LEN_MAX", MB_LEN_MAX);
#else
    printf("MB_LEN_MAX is not defined on this system.\n");
#endif

    printf("\n");
#ifdef FOPEN_MAX
    printf("FOPEN_MAX (max number of open files) = %d\n",FOPEN_MAX);
#else
    printf("FOPEN_MAX is not defined on the system.\n");
#endif

#ifdef TMP_MAX
    printf("TMP_MAX (max num of unique filenames generated by tmpnam()) = %d\n",
           TMP_MAX);
#else
    printf("TMP_MAX is not defined on the system.\n");
#endif

// This is a POSIX.1 name that should be equal to FOPEN_MAX:
#ifdef STREAM_MAX
    printf("STREAM_MAX (max number of open files) = %d\n",STREAM_MAX);
#else
    printf("STREAM_MAX is not defined on the system.\n");
#endif

    return 0;
   } 
